import type { CouchDbSettings } from './types'

export function buildCouchDbCompose(settings: CouchDbSettings): string {
  const port = settings.port || 5984
  const user = settings.username || 'admin'
  const password = settings.password || 'change-me'
  const database = settings.database || 'tasmotascope'

  return [
    "version: '3.8'",
    'services:',
    '  couchdb:',
    '    image: couchdb:3',
    '    container_name: tasmotascope-couchdb',
    '    restart: unless-stopped',
    '    ports:',
    `      - "${port}:5984"`,
    '    environment:',
    `      - COUCHDB_USER=${user}`,
    `      - COUCHDB_PASSWORD=${password}`,
    '    volumes:',
    '      - couchdb_data:/opt/couchdb/data',
    '    healthcheck:',
    '      test: ["CMD-SHELL", "curl -f http://localhost:5984/_up || exit 1"]',
    '      interval: 30s',
    '      timeout: 10s',
    '      retries: 5',
    '      start_period: 30s',
    '    networks:',
    '      - tasmotascope-network',
    '',
    '  couchdb-init:',
    '    image: curlimages/curl:latest',
    '    container_name: tasmotascope-couchdb-init',
    '    depends_on:',
    '      couchdb:',
    '        condition: service_healthy',
    '    command:',
    '      - sh',
    '      - -c',
    '      - |',
    "        echo '🚀 CouchDB Datenbank-Initialisierung gestartet...'",
    '        sleep 3',
    "        echo '🌐 Aktiviere CORS für Browser-Zugriff...'",
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_node/_local/_config/httpd/enable_cors -d '\"true\"'`,
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_node/_local/_config/cors/origins -d '\"*\"'`,
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_node/_local/_config/cors/credentials -d '\"true\"'`,
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_node/_local/_config/cors/methods -d '\"GET, PUT, POST, HEAD, DELETE, OPTIONS\"'`,
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_node/_local/_config/cors/headers -d '\"accept, authorization, content-type, origin, referer, x-csrf-token\"'`,
    "        echo '✅ CORS aktiviert'",
    "        echo '🔧 Erstelle System-Datenbanken...'",
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_users`,
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_replicator`,
    `        curl -X PUT http://${user}:${password}@couchdb:5984/_global_changes`,
    "        echo '✅ System-Datenbanken erstellt'",
    "        echo '📦 Erstelle App-Datenbank...'",
    `        curl -X PUT http://${user}:${password}@couchdb:5984/${database}`,
    "        echo '✅ App-Datenbank erstellt'",
    '    networks:',
    '      - tasmotascope-network',
    '    restart: "no"',
    'volumes:',
    '  couchdb_data:',
    '    driver: local',
    'networks:',
    '  tasmotascope-network:',
    '    driver: bridge',
    '    name: tasmotascope-network',
    '',
    `# Datenbank: ${database}`,
  ].join('\n')
}
